### ISSUE TITLE
CSS not loading correctly on the first time visiting the site

### ISSUE THREAD

**Issue by EricForgy** [FluxML/fluxml.github.io#65] opened 2020-07-01 18:37 UTC
Hi,

I notice this issue on several Julia-based websites and I am not sure what is the source of the problem, but @DhairyaLGandhi suggested starting here.

@DhairyaLGandhi posted the the latest article on Torch.jl (looks awesome!), but the first time I visit the page, the CSS is garbled. It looks like it thinks I'm on mobile or something.

![image](https://user-images.githubusercontent.com/8954730/86279263-96ebb000-bb8e-11ea-8a6b-712ac59baae9.png)

When I reload the page, everything is fine and every subsequent time I visit the site, the CSS is fine. It is only that very first visit that is garbled, but that first visit is the most important visit. Especially since I do a lot of Julia evangelizing and if I send the link to someone, I'd like to know what they see isn't garbled CSS. 

I can verify that the CSS is consistently garbled on the very first visit by loading the url into a fresh incognito window on Chrome.

This might seem minor, but first impressions are important, so I hope we can track down the source of this problem.

Cheers

**Comment by logankilpatrick** [comment] 2020-12-15 16:35
@EricForgy, I am closing this for now since my tests did not yield the same result and the website has just gone through extensive improvement (which likely resolved the issue). If this is still an issue, please re-open this with some steps to reproduce.

**Closed by logankilpatrick** 2020-12-15 16:35 UTC
